apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-infc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-infc@sha256:32207efdd411e8fad5414774ea373d33abd79af1e1f34b456a1939e73c42515c
        name: my-nodejs
        resources: {}
status: {}
